=== dzapatag99/3-trimestre/XML Y XSD/agenda2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="agenda">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="contacto" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="contacto">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="apellidos" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="fijo"/>
          <xs:element ref="movil"/>
        </xs:choice>
        <xs:element ref="email" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="sexo" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="pareja" minOccurs="0" maxOccurs="1"/>
        <xs:element name="comentarios" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="codigo" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="fijo">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:pattern value="[0-9]{9}"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="movil">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="empresa" type="xs:string" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="email">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="tipo" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="trabajo" />
                <xs:enumeration value="personal" />
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="sexo">
    <xs:complexType>
      <xs:choice>
        <xs:element name="hombre">
          <xs:complexType />
        </xs:element>
        <xs:element name="mujer">
          <xs:complexType />
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="pareja">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="codigo" type="xs:string" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== dzapatag99/3-trimestre/XML Y XSD/agenda2.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="agenda2.xsd">
  <contacto codigo="c001">
    <nombre>Juan</nombre>
    <apellidos>Marquez</apellidos>
    <movil empresa="movistar">656773221</movil>
    <movil>666123432</movil>
    <fijo>912343820</fijo>
    <movil>609398271</movil>
    <email tipo="trabajo">juan@ticarte.com</email>
    <sexo>
      <hombre />
    </sexo>
    <comentarios></comentarios>
  </contacto>
  <contacto codigo="c002">
    <nombre>Maria</nombre>
    <apellidos>Bonilla</apellidos>
    <movil empresa="movistar">665343092</movil>
    <movil>666232096</movil>
    <fijo>923430675</fijo>
    <email tipo="personal">maria@ticarte.com</email>
    <sexo>
      <mujer />
    </sexo>
    <pareja codigo="c001">Juan</pareja>
    <comentarios>Llamar solo por la mañana.</comentarios>
  </contacto>
</agenda>
