=== dzapatag99/3-trimestre/XML Y XSD/factura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="factura">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="3" />
        <xs:element name="periodo" type="xs:string" minOccurs="1" maxOccurs="1" fixed="mensual"/>
        <xs:element name="concepto" type="xs:string" minOccurs="1" maxOccurs="1" />
        <xs:element name="fecha" type="xs:date" minOccurs="1" maxOccurs="1"/>
        <xs:element name="hora" minOccurs="1" maxOccurs="1"/>
        <xs:element name="precio" type="xs:float" minOccurs="1" maxOccurs="1"/>
        <xs:element name="pagado" type="xs:boolean" minOccurs="1" maxOccurs="1" default="false"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== dzapatag99/3-trimestre/XML Y XSD/factura.xml
<?xml version="1.0" encoding="UTF-8" ?>
<factura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="factura.xsd">
  <nombre>Javier Toledano</nombre>
  <nombre>Javier Toledano</nombre>
  <nombre>Javier Toledano</nombre>
  <periodo>mensual</periodo>
  <concepto>Limpieza escalera y jard√≠n</concepto>
  <fecha>2021-02-04</fecha>
  <hora>23:55:15</hora>
  <precio>123.56</precio>
  <pagado>true</pagado>
</factura>
